### ISSUE TITLE
Publicar a versão v1.0

### ISSUE THREAD

**Issue by juliaschmitt09** [Hope-Games/Maze-of-the-past-#71]
O jogo deve preencher os seguintes requisitos:

- [x] Suporte a toque de tela #24;
- [x] Tela cheia #38;
- [x] Salas de partida #45;
- [x] Multijogador #46;
- [x] Publicação de conteúdo estático #54;
- [x] Publicação de conteúdo dinâmico #55;
- [x] Áudio sobre WebRTC #59;
- [x] Validação em teste alfa #60;
- [x] PWA #63

**Comment by juliaschmitt09** [comment]
Código considerado estável (o suficiente).
